name: Las Guas
slug: prodigal-las-guas
roaster: prodigal-coffee
rating: 4
origins:
  - Ecuador
flavors:
  - Fruity
  - Sweet
process: Washed
single_origin: true
currently_brewing: false
price_12oz: 18
notes: ""
image_url: https://storage.googleapis.com/johnverrone/coffee/prodigal-las-guas.jpg
created: 2024-02-14
