name: Espresso Milk Blend
slug: prodigal-espresso-milk-blend
roaster: prodigal-coffee
rating: 4
origins:
  - Brazil
  - Columbia
flavors: []
process: ""
single_origin: false
currently_brewing: false
price_12oz: 14.5
notes: ""
image_url: https://storage.googleapis.com/johnverrone/coffee/prodigal-espresso-milk-blend.jpg
created: 2024-02-14
